### ISSUE TITLE
Smoothing step leads to broken process pool

### ISSUE THREAD

**Issue by tsalo** [PennLINC/xcp_d_nicharts#3]
```
231205-20:31:06,743 nipype.workflow INFO:
	 [MultiProc] Running 1 tasks, and 16 jobs ready. Free memory (GB): 4.00/10.00, Free processors: 0/1.
                     Currently running:
                       * xcpd_wf.single_subject_1029037_wf.denoise_bold_wf.resd_smoothing_wf.nifti_smoothing
exception calling callback for <Future at 0x7fe095248f10 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

**Comment by tsalo** [comment]
I think the issue is that nilearn's smooth_img just can't handle the massive denoised file (~1 GB). I'm going to disable smoothing by default, but in XCP-D we might want to split the 4D file over volumes and smooth each one separately.

**Comment by tsalo** [comment]
I disabled smoothing, but got the same error with `_parcellate_data0`.
